  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - Volum:/volum:rw
      - ./things/index.html:/volum/www/index.html
      - ./things/default.conf:/etc/nginx/conf.d/default.conf
  server:
    image: centos:latest
    container_name: centos
    volumes:
      - Volum:/volum:rw
      - ./things/script:/volum/www/scr/script
    command: [/volum/www/scr/script]
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - Volum:/volum:rw
      - ./things/www:/var/www/:rw
      - ./things/www:/etc/letsencrypt/:rw
