  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - Volume:/Volum:rw
      - ./things/nginx/www:/Volum/nginx/www
      - ./things/nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  server:
    image: centos:latest
    container_name: centos
    volumes:
      - Volume:/Volum:rw
      - ./things/nginx/script:/Volum/nginx/www/scr/script
    command: [cat /Volum/nginx/www/scr/script]
    command: [/Volum/nginx/www/scr/script]

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - Volume:/Volum:rw
      - ./things/nginx/www:/Volum/nginx/www
      - ./things/certbot:/etc/letsencrypt
