# services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - Volum:/volum:rw
      - ./things/:/volum/www/
      - ./things/default.conf:/etc/nginx/conf.d/default.conf
  server:
    image: centos:latest
    container_name: centos
    volumes:
      - Volum:/volum:rw
      - ./things/script:/volum/www/scr/script
    command: [/volum/www/scr/script]
  certbot:
    image: certbot/certbot
    container_name: certbot
    ports:
      - "8443:443"
    volumes:
      - Volum:/volum:rw
